#!/bin/bash

echo "================================================"
echo "  Kesha's BetterMovement Mod - Project Info"
echo "================================================"
echo ""
echo "📦 Тип проекта: Minecraft Fabric Mod"
echo "🎯 Версия Minecraft: 1.21.1"
echo "☕ Требуется Java: 21+"
echo "🔧 Сборка: Gradle 8.10.2"
echo ""
echo "================================================"
echo "  Структура проекта:"
echo "================================================"
echo ""

tree -L 3 2>/dev/null || find . -type f -o -type d | head -50

echo ""
echo "================================================"
echo "  Основные файлы мода:"
echo "================================================"
echo ""

echo "📄 Основной класс мода:"
ls -lh src/main/java/com/kesha/bettermovement/BetterMovementMod.java 2>/dev/null && echo "   ✓ BetterMovementMod.java"

echo ""
echo "📄 Обработчик клавиш:"
ls -lh src/main/java/com/kesha/bettermovement/KeyInputHandler.java 2>/dev/null && echo "   ✓ KeyInputHandler.java"

echo ""
echo "📄 Миксин для движения:"
ls -lh src/main/java/com/kesha/bettermovement/mixin/KeyboardInputMixin.java 2>/dev/null && echo "   ✓ KeyboardInputMixin.java"

echo ""
echo "📄 Конфигурация:"
ls -lh src/main/java/com/kesha/bettermovement/ModConfig.java 2>/dev/null && echo "   ✓ ModConfig.java"

echo ""
echo "================================================"
echo "  Для компиляции мода:"
echo "================================================"
echo ""
echo "1. Локально (рекомендуется):"
echo "   ./gradlew build"
echo ""
echo "2. В Replit (с установленной Java 21):"
echo "   nix-shell -p jdk21 gradle"
echo "   export JAVA_HOME=\$(nix-build '<nixpkgs>' -A jdk21 --no-out-link)"
echo "   ./gradlew build"
echo ""
echo "3. Результат будет в:"
echo "   build/libs/bettermovement-1.0.0.jar"
echo ""
echo "================================================"
echo "  📖 Читайте COMPILE_INSTRUCTIONS.md для деталей"
echo "================================================"
